[package]
name = "k_means"
version = "0.1.0"
authors = ["Szymon Pilkowski <s.pilkowski@molecule.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
num-traits = "0.2"
